/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElAutocompleteFetchElAutocompleteRef_no: typeof import('element-plus/es')['ElAutocompleteFetchElAutocompleteRef_no']
  const ElAutocompleteFetchSuggestionsRef_no: typeof import('element-plus/es')['ElAutocompleteFetchSuggestionsRef_no']
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElRadio: typeof import('element-plus/es')['ElRadio']
  const ElSelectRemoteMethodRef_no: typeof import('element-plus/es')['ElSelectRemoteMethodRef_no']
}
